######################################################################
# Automatically generated by qmake (3.0) Tue May 24 17:02:25 2016
######################################################################

TEMPLATE = app
TARGET = input-panel
INCLUDEPATH += .

QT += core widgets

# Input
SOURCES += main.cpp window.cpp keyprocessor.cpp keydata.cpp
HEADERS += window.h keydata.h keyprocessor.h
